name: 'Apply patches'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: apply patches
      shell: bash
      run:
        cp V4.py main.py;
        for file in "patches/"*; do
          patch main.py "$file";
        done
    - name: Push
      shell: bash
      run: |
        git config user.name github-actions
        git config user.mail github-actions@github.com
        git add main.py;
        git commit -m 'Apply patches' || true
        git push || true
